"""
ab.py — A/B testing engine for PromptIQ.

Runs two prompt versions against the same set of test inputs,
collects outputs, judges each, and declares a winner with statistical
confidence and per-dimension breakdown.

Usage:
  result = ab_test(content_a, content_b, test_inputs, client_tuple)
"""

from __future__ import annotations
from dataclasses import dataclass, asdict
from typing import Optional

from .judge.runner import output_eval, OutputEval
from .judge.client import call, parse_json


@dataclass
class ABTestCase:
    test_input: str
    output_a: str
    output_b: str
    score_a: float      # avg of relevance + instruction_follow + quality
    score_b: float
    winner: str         # "a" | "b" | "tie"
    reasoning: str      # one sentence

    def to_dict(self) -> dict:
        return asdict(self)


@dataclass
class ABResult:
    prompt_a_label: str
    prompt_b_label: str
    test_cases: list[ABTestCase]
    wins_a: int
    wins_b: int
    ties: int
    overall_winner: str     # "a" | "b" | "tie"
    avg_score_a: float
    avg_score_b: float
    delta: float            # avg_score_b - avg_score_a
    summary: str            # 2-3 sentence synthesis

    def to_dict(self) -> dict:
        return {
            "prompt_a_label": self.prompt_a_label,
            "prompt_b_label": self.prompt_b_label,
            "test_cases":     [t.to_dict() for t in self.test_cases],
            "wins_a":         self.wins_a,
            "wins_b":         self.wins_b,
            "ties":           self.ties,
            "overall_winner": self.overall_winner,
            "avg_score_a":    self.avg_score_a,
            "avg_score_b":    self.avg_score_b,
            "delta":          self.delta,
            "summary":        self.summary,
        }


PAIRWISE_SYSTEM = """You are an expert evaluator comparing two AI outputs for the same prompt and input.

Output A was generated by Version A of a system prompt.
Output B was generated by Version B of the same system prompt.

Given the system prompt and user input, decide:
1. Which output is better? ("a", "b", or "tie")
2. One sentence of reasoning (be specific, cite actual content).

Return ONLY valid JSON:
{
  "winner": "a" | "b" | "tie",
  "reasoning": "one sentence"
}"""


def ab_test(
    content_a: str,
    content_b: str,
    test_inputs: list[str],
    client_tuple,
    label_a: str = "Version A",
    label_b: str = "Version B",
) -> ABResult:
    """Run full A/B test across all test inputs."""
    client, provider = client_tuple
    cases: list[ABTestCase] = []

    for inp in test_inputs:
        # Run both prompts
        eval_a = output_eval(content_a, inp, client_tuple)
        eval_b = output_eval(content_b, inp, client_tuple)

        # Pairwise judge
        user = (
            f"System prompt (both versions use this goal): judge which output is better.\n\n"
            f"User input:\n---\n{inp}\n---\n\n"
            f"Output A:\n---\n{eval_a.raw_output}\n---\n\n"
            f"Output B:\n---\n{eval_b.raw_output}\n---"
        )
        raw  = call(client, provider, PAIRWISE_SYSTEM, user)
        data = parse_json(raw)

        cases.append(ABTestCase(
            test_input = inp,
            output_a   = eval_a.raw_output,
            output_b   = eval_b.raw_output,
            score_a    = eval_a.avg_score,
            score_b    = eval_b.avg_score,
            winner     = data.get("winner",    "tie"),
            reasoning  = data.get("reasoning", ""),
        ))

    wins_a = sum(1 for c in cases if c.winner == "a")
    wins_b = sum(1 for c in cases if c.winner == "b")
    ties   = sum(1 for c in cases if c.winner == "tie")

    avg_a = round(sum(c.score_a for c in cases) / len(cases), 1) if cases else 0.0
    avg_b = round(sum(c.score_b for c in cases) / len(cases), 1) if cases else 0.0

    if wins_a > wins_b:
        overall_winner = "a"
    elif wins_b > wins_a:
        overall_winner = "b"
    else:
        overall_winner = "tie" if abs(avg_a - avg_b) < 0.5 else ("b" if avg_b > avg_a else "a")

    summary = _generate_summary(client, provider, label_a, label_b, cases, overall_winner, avg_a, avg_b)

    return ABResult(
        prompt_a_label = label_a,
        prompt_b_label = label_b,
        test_cases     = cases,
        wins_a         = wins_a,
        wins_b         = wins_b,
        ties           = ties,
        overall_winner = overall_winner,
        avg_score_a    = avg_a,
        avg_score_b    = avg_b,
        delta          = round(avg_b - avg_a, 1),
        summary        = summary,
    )


def _generate_summary(client, provider, label_a, label_b, cases, winner, avg_a, avg_b) -> str:
    system = "Summarize an A/B test result in 2 sentences. Be direct and quantitative."
    wins_a = sum(1 for c in cases if c.winner == "a")
    wins_b = sum(1 for c in cases if c.winner == "b")
    user = (
        f"A/B test of '{label_a}' vs '{label_b}' across {len(cases)} test cases.\n"
        f"Results: {label_a} won {wins_a}, {label_b} won {wins_b}.\n"
        f"Average scores: {label_a}={avg_a}/10, {label_b}={avg_b}/10.\n"
        f"Overall winner: {winner}."
    )
    return call(client, provider, system, user, max_tokens=200)
